- name: Setup Nginx default vhost
  template:
    src: www.domain.conf
    dest: "{{ nginx_vhost_available }}/{{ nginx_domain_name }}.conf"
  notify: Restart Nginx
  loop: "{{ nginx_domain_names }}"
  loop_control:
    loop_var: nginx_domain_name

- name: Create symling to hosts enabled.
  file:
    src: "{{ nginx_vhost_available }}/{{ nginx_domain_name }}.conf"
    dest: "{{ nginx_vhost_enabled }}/{{ nginx_domain_name }}.conf"
    state: link
  notify: Restart Nginx
  loop: "{{ nginx_domain_names }}"
  loop_control:
    loop_var: nginx_domain_name
