- debug:
    msg: "certbot -n --nginx {% for name in nginx_domain_names %} -d {{ name }} {% endfor %} --email {{ letsencrypt_notification_email }} --agree-tos"

- name: Execute certbot
  shell:
    cmd: "certbot -n --nginx {% for name in nginx_domain_names %} -d {{ name }} {% endfor %} --email {{ letsencrypt_notification_email }} --agree-tos"
      # notifiy: Restart Nginx
