---
# tasks file for role_app_nginx_letsencrypt_proxy/

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml" # For OpenSuSE Leap ansible_distribution_major_version is NA
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - always

- name: Include os independent variables.
  include_vars: "vars/main.yml"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: debug_info

- name: Install Nginx
  include: 01-nginx.yml

- name: Install letsencrypt
  include: 02-letsencrypt.yml

